class BaseCryptoError(Exception): ...


class AlbertiError(BaseCryptoError): ...
class AtbashError(BaseCryptoError): ...
class CaesarError(BaseCryptoError): ...
class CarganGrilleError(BaseCryptoError): ...
class DESError(BaseCryptoError): ...
class GOSTError(BaseCryptoError): ...
class GronsfeldError(BaseCryptoError): ...
class HillError(BaseCryptoError): ...
class PlayfairError(BaseCryptoError): ...
class PolybiusSquareError(BaseCryptoError): ...
class RichelieuError(BaseCryptoError): ...
class ScytaleError(BaseCryptoError): ...
class VernamError(BaseCryptoError): ...
class VigenereError(BaseCryptoError): ...
class XORError(BaseCryptoError): ...


class RC4Error(BaseCryptoError): ...


class AutocorrError(BaseCryptoError): ...
class FreqAnalysisError(BaseCryptoError): ...
class ICError(BaseCryptoError): ...
