# Form implementation generated from reading ui file 'playfair.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_playfair(object):
    def setupUi(self, playfair):
        playfair.setObjectName("playfair")
        playfair.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(playfair)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_box_input = QtWidgets.QGroupBox(playfair)
        self.group_box_input.setObjectName("group_box_input")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.group_box_input)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.text_edit_input = QtWidgets.QTextEdit(self.group_box_input)
        self.text_edit_input.setObjectName("text_edit_input")
        self.verticalLayout_32.addWidget(self.text_edit_input)
        self.verticalLayout.addWidget(self.group_box_input)
        self.horizontal_layout_1 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_1.setContentsMargins(8, -1, -1, -1)
        self.horizontal_layout_1.setObjectName("horizontal_layout_1")
        self.label_key = QtWidgets.QLabel(playfair)
        self.label_key.setObjectName("label_key")
        self.horizontal_layout_1.addWidget(self.label_key)
        self.line_edit_key = QtWidgets.QLineEdit(playfair)
        self.line_edit_key.setObjectName("line_edit_key")
        self.horizontal_layout_1.addWidget(self.line_edit_key)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontal_layout_1.addItem(spacerItem)
        self.combo_box_mode = QtWidgets.QComboBox(playfair)
        self.combo_box_mode.setObjectName("combo_box_mode")
        self.combo_box_mode.addItem("")
        self.combo_box_mode.addItem("")
        self.horizontal_layout_1.addWidget(self.combo_box_mode)
        self.verticalLayout.addLayout(self.horizontal_layout_1)
        self.horizontal_layout_2 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_2.setObjectName("horizontal_layout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontal_layout_2.addItem(spacerItem1)
        self.button_make = QtWidgets.QPushButton(playfair)
        self.button_make.setMinimumSize(QtCore.QSize(100, 30))
        self.button_make.setObjectName("button_make")
        self.horizontal_layout_2.addWidget(self.button_make)
        self.verticalLayout.addLayout(self.horizontal_layout_2)
        self.group_box_output = QtWidgets.QGroupBox(playfair)
        self.group_box_output.setObjectName("group_box_output")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.group_box_output)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.text_edit_output = QtWidgets.QTextEdit(self.group_box_output)
        self.text_edit_output.setReadOnly(True)
        self.text_edit_output.setObjectName("text_edit_output")
        self.verticalLayout_31.addWidget(self.text_edit_output)
        self.verticalLayout.addWidget(self.group_box_output)

        self.retranslateUi(playfair)
        QtCore.QMetaObject.connectSlotsByName(playfair)

    def retranslateUi(self, playfair):
        _translate = QtCore.QCoreApplication.translate
        playfair.setWindowTitle(_translate("playfair", "Form"))
        self.group_box_input.setTitle(_translate("playfair", "Input text"))
        self.label_key.setText(_translate("playfair", "Key:"))
        self.combo_box_mode.setItemText(0, _translate("playfair", "Encrypt"))
        self.combo_box_mode.setItemText(1, _translate("playfair", "Decrypt"))
        self.button_make.setText(_translate("playfair", "Make"))
        self.group_box_output.setTitle(_translate("playfair", "Output text"))
