# Form implementation generated from reading ui file 'atbash.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_atbash(object):
    def setupUi(self, atbash):
        atbash.setObjectName("atbash")
        atbash.resize(654, 489)
        self.verticalLayout = QtWidgets.QVBoxLayout(atbash)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_box_input = QtWidgets.QGroupBox(atbash)
        self.group_box_input.setObjectName("group_box_input")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.group_box_input)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.text_edit_input = QtWidgets.QTextEdit(self.group_box_input)
        self.text_edit_input.setObjectName("text_edit_input")
        self.verticalLayout_7.addWidget(self.text_edit_input)
        self.verticalLayout.addWidget(self.group_box_input)
        self.horizontal_layout_1 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_1.setSpacing(12)
        self.horizontal_layout_1.setObjectName("horizontal_layout_1")
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontal_layout_1.addItem(spacerItem)
        self.button_make = QtWidgets.QPushButton(atbash)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_make.sizePolicy().hasHeightForWidth())
        self.button_make.setSizePolicy(sizePolicy)
        self.button_make.setMinimumSize(QtCore.QSize(100, 30))
        self.button_make.setObjectName("button_make")
        self.horizontal_layout_1.addWidget(self.button_make)
        self.verticalLayout.addLayout(self.horizontal_layout_1)
        self.group_box_output = QtWidgets.QGroupBox(atbash)
        self.group_box_output.setObjectName("group_box_output")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.group_box_output)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.text_edit_output = QtWidgets.QTextEdit(self.group_box_output)
        self.text_edit_output.setReadOnly(True)
        self.text_edit_output.setObjectName("text_edit_output")
        self.verticalLayout_6.addWidget(self.text_edit_output)
        self.verticalLayout.addWidget(self.group_box_output)

        self.retranslateUi(atbash)
        QtCore.QMetaObject.connectSlotsByName(atbash)

    def retranslateUi(self, atbash):
        _translate = QtCore.QCoreApplication.translate
        atbash.setWindowTitle(_translate("atbash", "Form"))
        self.group_box_input.setTitle(_translate("atbash", "Input text"))
        self.button_make.setText(_translate("atbash", "Make"))
        self.group_box_output.setTitle(_translate("atbash", "Output text"))
