# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_about(object):
    def setupUi(self, about):
        about.setObjectName("about")
        about.resize(500, 400)
        about.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(about)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_topic = QtWidgets.QLabel(about)
        self.label_topic.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_topic.setObjectName("label_topic")
        self.verticalLayout.addWidget(self.label_topic)
        spacerItem1 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontal_layout_links = QtWidgets.QHBoxLayout()
        self.horizontal_layout_links.setObjectName("horizontal_layout_links")
        self.button_vk = QtWidgets.QPushButton(about)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_vk.sizePolicy().hasHeightForWidth())
        self.button_vk.setSizePolicy(sizePolicy)
        self.button_vk.setStyleSheet("")
        self.button_vk.setObjectName("button_vk")
        self.horizontal_layout_links.addWidget(self.button_vk)
        self.button_tg = QtWidgets.QPushButton(about)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_tg.sizePolicy().hasHeightForWidth())
        self.button_tg.setSizePolicy(sizePolicy)
        self.button_tg.setStyleSheet("")
        self.button_tg.setIconSize(QtCore.QSize(16, 16))
        self.button_tg.setCheckable(False)
        self.button_tg.setFlat(False)
        self.button_tg.setObjectName("button_tg")
        self.horizontal_layout_links.addWidget(self.button_tg)
        self.button_github = QtWidgets.QPushButton(about)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_github.sizePolicy().hasHeightForWidth())
        self.button_github.setSizePolicy(sizePolicy)
        self.button_github.setStyleSheet("")
        self.button_github.setObjectName("button_github")
        self.horizontal_layout_links.addWidget(self.button_github)
        self.verticalLayout.addLayout(self.horizontal_layout_links)

        self.retranslateUi(about)
        QtCore.QMetaObject.connectSlotsByName(about)

    def retranslateUi(self, about):
        _translate = QtCore.QCoreApplication.translate
        about.setWindowTitle(_translate("about", "Form"))
        self.label_topic.setText(_translate("about", "<p align=\"center\">\n"
"    <img src=\"resources/icons/crypto-methods.png\" alt=\"preview\" height=\"128\" width=\"128\">\n"
"</p>\n"
"\n"
"<div>\n"
"    <h1 align=\"center\">Crypto-methods</h1>\n"
"    <h2 align=\"center\">Encrypt | Decrypt</h2>\n"
"    <p align=\"center\">Laboratory work on cryptographic methods of information protection</p>\n"
"</div>"))
        self.button_vk.setText(_translate("about", "vk.com/vasilypht"))
        self.button_tg.setText(_translate("about", "t.me/vasilypht"))
        self.button_github.setText(_translate("about", "github.com/vasilypht"))
